### ISSUE TITLE
Readme needs a user story

### ISSUE THREAD

**Issue by azuryte5** [azuryte5/Nutrition-Sustenance-Value#1]
Build a user story for project 1
![user stories](https://user-images.githubusercontent.com/85147307/135284061-7b55490e-2765-4c0a-805c-97b9820159b4.png)

**Comment by azuryte5** [comment]
Discussed @ Wednesday's Google meet:

Our user will be someone who makes an account so some preset information is already gathered such as (children to feed?, Access to store food?, ...) 

Then based on when they use the app we will assume that they are under a time crunch where they are 1) hungry 2) have little time to decide how to proceed. Based on a quick criteria maybe they a) have access to food already b) have others to feed c) have already eaten out today d)could visit a grocery store to pick up a quick <5 ingredients. 

We talked about a carousal, catalogue of options that we could direct the user to be like (Input current data -> oh, here go to a store and cook this quick meal)

The intent is to battle marketing app influencers that are encouraging the user to just skipthedishes or eat fastfood. What other cost effective/ quick actions are there. Some people don't have the time to plan meals ahead, or have the time to rush home and spend an hour cooking. 
 
 We can build a couple quick solution options and help save the user value, time and improve their health by assisting them follow the Canada food guide.

**Comment by valerrianna** [comment]
As an individual interested in healthy eating with a busy lifestyle,

I want an app that generates recipes that are convenient to make with what is available in the fridge while still having a balanced meal.

So that I can reduce food waste, while avoiding unhealthy fast food chains and acquiring all essential nutrients for my body.

**Comment by azuryte5** [comment]
I was thinking we needed the When/then statements but was informed by the team this might not be the case. User story looks great. 

added image to readme, but I need to doublecheck formatting of the img source.
