### ISSUE TITLE
dropdowns for cuisine + health 

### ISSUE THREAD

**Issue by azuryte5** [azuryte5/Nutrition-Sustenance-Value#13]
creating the dropdowns and adding the choices (multiple)

**Comment by azuryte5** [comment]
I got the dropdowns plug-ed in and coded to be attached to api

**Comment by jhugray** [comment]
Drop downs have been completed - buttons combined to have one submit for all the user inputs. Input from the drop down parameters gets used in the API fetch to generate recipes specific to the user's parameters.
