### ISSUE TITLE
Project Allocation

### ISSUE THREAD

**Issue by azuryte5** [azuryte5/Nutrition-Sustenance-Value#2]
Who is going to to what? Dividing work up 5 ways 

![Screenshot 2021-09-28 191657](https://user-images.githubusercontent.com/85147307/135284252-85de4825-a39d-4225-a5fc-6d9b7a624175.png)

**Comment by azuryte5** [comment]
![tracking skillsets](https://user-images.githubusercontent.com/85147307/135291096-3ab2ab0f-72bd-4f07-9ae9-4fe5f034d455.png)

**Comment by azuryte5** [comment]
![60-feature-branch](https://user-images.githubusercontent.com/85147307/135291860-33e8ee46-b30a-4b36-80c4-4e7bce0ebdb9.png)
This came to my mind in week 2 that I asked about in class. I'm still trying to understand this image and how we are to build content vertically that will work together and build something in less than 2 weeks.

**Comment by azuryte5** [comment]
During Wednesday's Meeting we tasked the following:
-  @azuryte5 look up API's and data collection (Found How to access Canada Nutrient file and Edamam)
-  @valerrianna sending a color palette to @Randolph who will work on a wireframe (No red, harsh colours)
-  @valerrianna to work on user-story/readme
- @azuryte5 will present and demo working product on during Wk 8

- By end of Thursday September 30th we need to solidify our product vision, user story and ideal user experience
For the other Members: @Jess, @Skyler 
- there is still lots to decide.  have a look at the to-do's [https://github.com/azuryte5/Nutrition-Sustenance-Value/projects/1](url)

**Comment by valerrianna** [comment]
Potential color scheme (earthy/warm colours)

**Comment by azuryte5** [comment]
tasks distributed and follow up meeting planned for Saturday evening
